title: Research Project
description: Bilingual research website on GitHub Pages
url: "https://naoumov-ilia.github.io"
baseurl: ""

lang: ru

markdown: kramdown
theme: null

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      
exclude:
  - README.md
  - LICENSE
